# Generated by Django 4.2.30 on 2026-06-17 15:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('parent_type', models.CharField(choices=[('theory_ce', 'Theory CE'), ('theory_ese', 'Theory ESE'), ('practical_ce', 'Practical CE'), ('practical_ese', 'Practical ESE'), ('tutorial_ce', 'Tutorial CE'), ('tutorial_ese', 'Tutorial ESE')], max_length=20, verbose_name='Parent Component Type')),
                ('formula_string', models.TextField(help_text='Mathematical expression using variable names (e.g., (I1 + I2)/2 + FE)', verbose_name='Formula')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_archived', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_formulas', to='master_data.subject')),
            ],
            options={
                'verbose_name': 'Component Formula',
                'verbose_name_plural': 'Component Formulas',
                'unique_together': {('subject', 'parent_type')},
            },
        ),
        migrations.CreateModel(
            name='AssessmentComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('parent_type', models.CharField(choices=[('theory_ce', 'Theory CE'), ('theory_ese', 'Theory ESE'), ('practical_ce', 'Practical CE'), ('practical_ese', 'Practical ESE'), ('tutorial_ce', 'Tutorial CE'), ('tutorial_ese', 'Tutorial ESE')], max_length=20, verbose_name='Parent Component Type')),
                ('name', models.CharField(help_text='e.g., Internal 1', max_length=100, verbose_name='Component Name')),
                ('variable_name', models.CharField(help_text='Short name used in formulas (e.g., I1)', max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z_][a-zA-Z0-9_]*$', 'Only alphanumeric and underscores allowed. Must start with a letter.')], verbose_name='Variable Name')),
                ('max_marks', models.PositiveIntegerField(help_text='The conducted maximum marks for this component.', verbose_name='Maximum Marks')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_archived', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_components', to='master_data.subject')),
            ],
            options={
                'verbose_name': 'Assessment Component',
                'verbose_name_plural': 'Assessment Components',
                'ordering': ['subject', 'parent_type', 'name'],
                'unique_together': {('subject', 'parent_type', 'variable_name'), ('subject', 'parent_type', 'name')},
            },
        ),
    ]
