# Generated by Django 6.0.4 on 2026-06-25 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ComponentFormula",
        ),
    ]
