# Generated by Django 6.0.4 on 2026-06-23 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("master_data", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_archived", models.BooleanField(db_index=True, default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "roll_no",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Roll Number"
                    ),
                ),
                (
                    "enrollment_no",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Enrollment Number"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Student Name")),
                ("semester", models.PositiveIntegerField()),
                (
                    "lab_batch_no",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Lab Batch No"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                (
                    "display_no",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Display No"
                    ),
                ),
                (
                    "admission_application_no",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Admission Application No",
                    ),
                ),
                (
                    "phone_1",
                    models.CharField(blank=True, max_length=20, verbose_name="Phone 1"),
                ),
                (
                    "phone_2",
                    models.CharField(blank=True, max_length=20, verbose_name="Phone 2"),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_archived",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "division",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="students",
                        to="master_data.division",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="students",
                        to="master_data.program",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student",
                "verbose_name_plural": "Students",
                "ordering": ["program", "semester", "roll_no"],
            },
        ),
    ]
