# Generated by Django 6.0.4 on 2026-06-29 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0002_faculty_master_and_allocation"),
        ("master_data", "0001_initial"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={
                "ordering": ["academic_year", "class_name", "name"],
                "verbose_name": "Student",
                "verbose_name_plural": "Students",
            },
        ),
        migrations.AddField(
            model_name="student",
            name="academic_year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="academic.academicyear",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="batch",
            field=models.CharField(blank=True, max_length=10, verbose_name="Batch"),
        ),
        migrations.AddField(
            model_name="student",
            name="class_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Class Name"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="enrollment_no",
            field=models.CharField(max_length=50, verbose_name="Enrollment Number"),
        ),
        migrations.AlterField(
            model_name="student",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="students",
                to="master_data.program",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="roll_no",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Roll Number"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="semester",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="student",
            unique_together={("academic_year", "enrollment_no")},
        ),
    ]
