# Generated by Django 6.0.4 on 2026-06-23 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("master_data", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssessmentScheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_archived", models.BooleanField(db_index=True, default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "theory_ce",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Theory CE Max Marks"
                    ),
                ),
                (
                    "theory_ese",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Theory ESE Max Marks"
                    ),
                ),
                (
                    "practical_ce",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Practical CE Max Marks"
                    ),
                ),
                (
                    "practical_ese",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Practical ESE Max Marks"
                    ),
                ),
                (
                    "tutorial_ce",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Tutorial CE Max Marks"
                    ),
                ),
                (
                    "tutorial_ese",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Tutorial ESE Max Marks"
                    ),
                ),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_archived",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessment_scheme",
                        to="master_data.subject",
                        verbose_name="Subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assessment Scheme",
                "verbose_name_plural": "Assessment Schemes",
            },
        ),
        migrations.CreateModel(
            name="CurriculumMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_archived", models.BooleanField(db_index=True, default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("semester", models.PositiveIntegerField(verbose_name="Semester")),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_archived",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curriculum_mappings",
                        to="master_data.program",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curriculum_mappings",
                        to="master_data.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Curriculum Mapping",
                "verbose_name_plural": "Curriculum Mappings",
                "ordering": ["program", "semester", "subject"],
                "unique_together": {("subject", "program", "semester")},
            },
        ),
    ]
