"""
Google Drive service for PDF storage.
Handles upload, download, and deletion of files in Google Drive.

Setup Instructions:
1. Go to Google Cloud Console → Create a project
2. Enable the Google Drive API
3. Create OAuth 2.0 credentials (or Service Account for server-to-server)
4. Download credentials.json and place in project root
5. Set GOOGLE_DRIVE_CREDENTIALS_FILE and GOOGLE_DRIVE_FOLDER_ID in .env
"""
import logging
from django.conf import settings

logger = logging.getLogger(__name__)


class GoogleDriveService:
    """
    Service for interacting with Google Drive API.
    All PDF files generated by the system are stored in Drive.
    Only metadata and links are stored in the database.
    """

    def __init__(self):
        self._service = None
        self._initialized = False

    def _get_service(self):
        """Initialize and return the Google Drive API service."""
        if self._initialized:
            return self._service

        credentials_file = settings.GOOGLE_DRIVE_CREDENTIALS_FILE

        if not credentials_file:
            logger.warning(
                'Google Drive credentials file not configured. '
                'File uploads will be stored locally as fallback.'
            )
            self._initialized = True
            return None

        try:
            from google.oauth2.service_account import Credentials
            from googleapiclient.discovery import build

            credentials = Credentials.from_service_account_file(
                credentials_file,
                scopes=['https://www.googleapis.com/auth/drive.file']
            )
            self._service = build('drive', 'v3', credentials=credentials)
            self._initialized = True
            logger.info('Google Drive service initialized successfully.')
            return self._service
        except Exception as e:
            logger.error(f'Failed to initialize Google Drive service: {e}')
            self._initialized = True
            return None

    def upload_file(self, file_path, file_name, mime_type='application/pdf'):
        """
        Upload a file to Google Drive.

        Args:
            file_path: Path to the local file
            file_name: Name to give the file in Drive
            mime_type: MIME type of the file

        Returns:
            dict: {'file_id': str, 'file_link': str} or None on failure
        """
        service = self._get_service()

        if not service:
            logger.warning(f'Google Drive not configured. Skipping upload for: {file_name}')
            return None

        try:
            from googleapiclient.http import MediaFileUpload

            file_metadata = {
                'name': file_name,
                'parents': [settings.GOOGLE_DRIVE_FOLDER_ID] if settings.GOOGLE_DRIVE_FOLDER_ID else [],
            }

            media = MediaFileUpload(file_path, mimetype=mime_type, resumable=True)

            file = service.files().create(
                body=file_metadata,
                media_body=media,
                fields='id, webViewLink'
            ).execute()

            result = {
                'file_id': file.get('id'),
                'file_link': file.get('webViewLink'),
            }

            logger.info(f'File uploaded to Google Drive: {file_name} (ID: {result["file_id"]})')
            return result

        except Exception as e:
            logger.error(f'Failed to upload file to Google Drive: {e}')
            return None

    def delete_file(self, file_id):
        """
        Delete a file from Google Drive.

        Args:
            file_id: Google Drive file ID

        Returns:
            bool: True if successful, False otherwise
        """
        service = self._get_service()

        if not service:
            return False

        try:
            service.files().delete(fileId=file_id).execute()
            logger.info(f'File deleted from Google Drive: {file_id}')
            return True
        except Exception as e:
            logger.error(f'Failed to delete file from Google Drive: {e}')
            return False

    def get_file_link(self, file_id):
        """
        Get the web view link for a file.

        Args:
            file_id: Google Drive file ID

        Returns:
            str: Web view link or None
        """
        service = self._get_service()

        if not service:
            return None

        try:
            file = service.files().get(fileId=file_id, fields='webViewLink').execute()
            return file.get('webViewLink')
        except Exception as e:
            logger.error(f'Failed to get file link from Google Drive: {e}')
            return None


# Singleton instance
google_drive_service = GoogleDriveService()
