# Generated by Django 6.0.4 on 2026-06-23 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TextContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "content_type",
                    models.CharField(
                        default="text",
                        help_text="Content format: text, html, csv, json",
                        max_length=50,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="The full text content stored in the database.",
                        verbose_name="Content",
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        choices=[
                            ("question_paper", "Question Paper"),
                            ("seating_plan", "Seating Plan"),
                            ("duty_chart", "Duty Chart"),
                            ("marks_report", "Marks Report"),
                            ("schedule", "Schedule"),
                            ("analysis", "Analysis Report"),
                            ("general", "General"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "related_object_id",
                    models.CharField(
                        blank=True,
                        help_text="ID of the related entity (exam, subject, etc.)",
                        max_length=100,
                    ),
                ),
                ("related_model", models.CharField(blank=True, max_length=100)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_contents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Text Content",
                "verbose_name_plural": "Text Contents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("archive", "Archive"),
                            ("unarchive", "Unarchive"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("import", "Import"),
                            ("export", "Export"),
                            ("generate", "Generate"),
                            ("lock", "Lock"),
                            ("unlock", "Unlock"),
                            ("submit", "Submit"),
                            ("approve", "Approve"),
                            ("reject", "Reject"),
                            ("assign", "Assign"),
                            ("upload", "Upload"),
                            ("download", "Download"),
                            ("password_change", "Password Change"),
                            ("password_reset", "Password Reset"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "model_name",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("object_id", models.CharField(blank=True, max_length=100)),
                ("object_repr", models.CharField(blank=True, max_length=255)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "action"], name="core_auditl_user_id_4f5b78_idx"
                    ),
                    models.Index(
                        fields=["model_name", "object_id"],
                        name="core_auditl_model_n_3fb686_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="core_auditl_created_1a76fa_idx"
                    ),
                ],
            },
        ),
    ]
