# Generated by Django 4.2.30 on 2026-06-25 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notificationlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textcontent',
            name='module',
            field=models.CharField(choices=[('question_paper', 'Question Paper'), ('seating_plan', 'Seating Plan'), ('duty_chart', 'Duty Chart'), ('marks_report', 'Marks Report'), ('schedule', 'Schedule'), ('analysis', 'Analysis Report'), ('general', 'General'), ('reports_seating_arrangement', 'Report: Seating Arrangement'), ('reports_duty_chart', 'Report: Duty Chart'), ('reports_marks_summary', 'Report: Marks Summary'), ('reports_result_analysis', 'Report: Result Analysis'), ('reports_exam_schedule', 'Report: Exam Schedule'), ('reports_question_paper', 'Report: Question Paper')], db_index=True, max_length=30),
        ),
    ]
