# Generated by Django 6.0.4 on 2026-06-23 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("exams", "0001_initial"),
        ("master_data", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionPaper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_archived", models.BooleanField(db_index=True, default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("semester", models.PositiveIntegerField()),
                ("date", models.DateField(blank=True, null=True)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("total_marks", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_archived",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_question_papers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_papers",
                        to="exams.exam",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_papers",
                        to="master_data.program",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_papers",
                        to="master_data.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Question Paper",
                "verbose_name_plural": "Question Papers",
                "ordering": ["-created_at"],
                "unique_together": {("exam", "subject", "program")},
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_archived", models.BooleanField(db_index=True, default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "question_number",
                    models.CharField(help_text="e.g., Q1(a), Q2(b)", max_length=20),
                ),
                ("text", models.TextField(verbose_name="Question Text")),
                ("marks", models.PositiveIntegerField()),
                (
                    "co_mapping",
                    models.CharField(
                        help_text="e.g., CO1, CO2",
                        max_length=50,
                        verbose_name="CO Mapping",
                    ),
                ),
                (
                    "btl_mapping",
                    models.CharField(
                        help_text="e.g., L1, L2, L3",
                        max_length=50,
                        verbose_name="BTL Mapping",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_archived",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="question_papers.questionpaper",
                    ),
                ),
            ],
            options={
                "verbose_name": "Question",
                "verbose_name_plural": "Questions",
                "ordering": ["order", "created_at"],
            },
        ),
    ]
