# Generated by Django 6.0.4 on 2026-07-02 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question_papers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="questionpaper",
            name="assessment_component",
            field=models.CharField(
                choices=[("Internal 1", "Internal 1"), ("Internal 2", "Internal 2")],
                default="Internal 1",
                help_text="Only Internal 1 and Internal 2 are supported for Question Paper generation.",
                max_length=20,
                verbose_name="Assessment Component",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="btl_mapping",
            field=models.CharField(
                choices=[
                    ("BTL1", "BTL1 - Remembering"),
                    ("BTL2", "BTL2 - Understanding"),
                    ("BTL3", "BTL3 - Applying"),
                    ("BTL4", "BTL4 - Analyzing"),
                    ("BTL5", "BTL5 - Evaluating"),
                    ("BTL6", "BTL6 - Creating"),
                ],
                max_length=10,
                verbose_name="BTL Mapping",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="co_mapping",
            field=models.CharField(
                choices=[
                    ("CO1", "CO1"),
                    ("CO2", "CO2"),
                    ("CO3", "CO3"),
                    ("CO4", "CO4"),
                    ("CO5", "CO5"),
                ],
                max_length=10,
                verbose_name="CO Mapping",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="marks",
            field=models.PositiveIntegerField(
                default=5, help_text="Hardcoded to 5 marks per question."
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_number",
            field=models.CharField(help_text="e.g., Q1, Q2", max_length=20),
        ),
        migrations.CreateModel(
            name="QuestionPaperTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_archived", models.BooleanField(db_index=True, default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(default="Standard Template", max_length=100)),
                (
                    "header_html",
                    models.TextField(
                        default="<div style='text-align:center;'><h1>College Name</h1><h2>{{ subject_code }} - {{ subject_name }}</h2></div>",
                        help_text="Use placeholders like {{ subject_code }}, {{ date }}, {{ questions }}, etc.",
                        verbose_name="Header HTML Template",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_archived",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Question Paper Template",
                "verbose_name_plural": "Question Paper Templates",
                "ordering": ["-created_at"],
            },
        ),
    ]
