# Generated by Django 6.0.4 on 2026-07-02 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question_papers", "0002_questionpaper_assessment_component_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionpaper",
            name="instructions",
            field=models.TextField(
                default="All questions compulsory.\nUse of scientific calculator is allowed.\nDraw neat and clean drawings/figure & assume suitable data if necessary.",
                verbose_name="Instructions",
            ),
        ),
    ]
