# Generated by Django 6.0.4 on 2026-06-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marks", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentmark",
            name="is_absent",
        ),
        migrations.AddField(
            model_name="studentmark",
            name="status",
            field=models.CharField(
                choices=[
                    ("Present", "Present"),
                    ("AB", "Absent"),
                    ("UFM", "Unfair Means"),
                ],
                default="Present",
                max_length=10,
            ),
        ),
    ]
