# Generated by Django 4.2.30 on 2026-06-29 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
        ('marks', '0002_remove_studentmark_is_absent_studentmark_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='marksentrytask',
            name='semester_subject',
            field=models.ForeignKey(blank=True, help_text='Links this task to the academic structure for dynamic marks components.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marks_tasks', to='academic.semestersubject', verbose_name='Semester Subject'),
        ),
    ]
