# Generated by Django 6.0.4 on 2026-06-29 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0002_faculty_master_and_allocation"),
        ("exams", "0004_alter_exam_options_exam_academic_year_ref_and_more"),
        ("marks", "0003_marksentrytask_semester_subject"),
        ("master_data", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="marksentrytask",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="marksentrytask",
            name="teaching_assignment",
            field=models.ForeignKey(
                blank=True,
                help_text="Links this task to the specific class and batch assignment.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="marks_tasks",
                to="academic.facultyteachingassignment",
                verbose_name="Teaching Assignment",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="marksentrytask",
            unique_together={
                ("exam", "subject", "division", "teaching_assignment", "faculty")
            },
        ),
    ]
