# Generated by Django 6.0.4 on 2026-07-01 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0005_markssubcomponent_number_of_questions"),
        ("exams", "0005_alter_exam_exam_type"),
        ("marks", "0004_alter_marksentrytask_unique_together_and_more"),
        ("master_data", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="marksentrytask",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="marksentrytask",
            name="sub_component",
            field=models.ForeignKey(
                blank=True,
                help_text="If this task is specifically for a sub-component like Internal 1.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="marks_tasks",
                to="academic.markssubcomponent",
                verbose_name="Marks Sub-Component",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="marksentrytask",
            unique_together={
                (
                    "exam",
                    "subject",
                    "division",
                    "teaching_assignment",
                    "faculty",
                    "sub_component",
                )
            },
        ),
    ]
