# Generated by Django 4.2.30 on 2026-06-29 04:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text='Format: YYYY-YY (e.g., 2023-24)', max_length=7, unique=True, validators=[django.core.validators.RegexValidator(message='Format must be YYYY-YY (e.g., 2023-24)', regex='^\\d{4}-\\d{2}$')], verbose_name='Academic Year')),
                ('description', models.TextField(blank=True, help_text='Optional description or notes for this academic year.', verbose_name='Description')),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('archived', 'Archived')], default='active', max_length=10, verbose_name='Status')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_archived', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Academic Year',
                'verbose_name_plural': 'Academic Years',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('number', models.PositiveIntegerField(help_text='e.g., 1, 2, 3, 4, 5, 6', verbose_name='Semester Number')),
                ('name', models.CharField(help_text='e.g., Semester 1', max_length=50, verbose_name='Semester Name')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='academic.academicyear', verbose_name='Academic Year')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_archived', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Semester',
                'verbose_name_plural': 'Semesters',
                'ordering': ['academic_year', 'number'],
                'unique_together': {('academic_year', 'number')},
            },
        ),
        migrations.CreateModel(
            name='SemesterSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('subject_code', models.CharField(help_text='Snapshot of the subject code at import time.', max_length=50, verbose_name='Subject Code')),
                ('subject_name', models.CharField(help_text='Snapshot of the subject name at import time.', max_length=255, verbose_name='Subject Name')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_archived', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_subjects', to='academic.semester', verbose_name='Semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='semester_subjects', to='master_data.subject', verbose_name='Subject')),
            ],
            options={
                'verbose_name': 'Semester Subject',
                'verbose_name_plural': 'Semester Subjects',
                'ordering': ['semester', 'subject_code'],
                'unique_together': {('semester', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='AcademicStructureImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('original_filename', models.CharField(max_length=255, verbose_name='Original Filename')),
                ('file_format', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'Excel (XLSX)')], max_length=4, verbose_name='File Format')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial')], default='success', max_length=10, verbose_name='Import Status')),
                ('summary', models.JSONField(blank=True, default=dict, help_text='Statistics: semesters_created, subjects_created, components_created, etc.', verbose_name='Import Summary')),
                ('error_log', models.JSONField(blank=True, default=list, help_text='List of row-level errors encountered during import.', verbose_name='Error Log')),
                ('program_name', models.CharField(blank=True, help_text='Program name auto-detected from file title.', max_length=255, verbose_name='Detected Program')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='academic.academicyear', verbose_name='Academic Year')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_archived', to=settings.AUTH_USER_MODEL)),
                ('imported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_imports', to=settings.AUTH_USER_MODEL, verbose_name='Imported By')),
            ],
            options={
                'verbose_name': 'Academic Structure Import',
                'verbose_name_plural': 'Academic Structure Imports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarksComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text='e.g., Theory CE, Practical ESE, Viva, Project', max_length=100, verbose_name='Component Name')),
                ('slug', models.SlugField(help_text='Auto-generated URL-safe identifier used as key in marks JSONField.', max_length=100, verbose_name='Component Slug')),
                ('max_marks', models.PositiveIntegerField(help_text='Maximum obtainable marks for this component.', verbose_name='Maximum Marks')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Controls the order components appear in the UI.', verbose_name='Display Order')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_archived', to=settings.AUTH_USER_MODEL)),
                ('semester_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks_components', to='academic.semestersubject', verbose_name='Semester Subject')),
            ],
            options={
                'verbose_name': 'Marks Component',
                'verbose_name_plural': 'Marks Components',
                'ordering': ['semester_subject', 'display_order', 'name'],
                'unique_together': {('semester_subject', 'slug')},
            },
        ),
    ]
