# Generated by Django 4.2.30 on 2026-06-29 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('faculty_name', models.CharField(help_text='Full name as it appears in official records.', max_length=255, verbose_name='Faculty Name')),
                ('short_form', models.CharField(blank=True, help_text='e.g., BBB, SJS, PSM — used for matching in allocation files.', max_length=20, verbose_name='Short Form / Alias')),
                ('email', models.EmailField(help_text='Primary identity for login, notifications, and audit.', max_length=254, verbose_name='Official Email ID')),
                ('employee_code', models.CharField(blank=True, help_text='HR employee ID, if available.', max_length=50, verbose_name='Employee Code')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Department')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this faculty is currently active for this academic year.', verbose_name='Active')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_members', to='academic.academicyear', verbose_name='Academic Year')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_archived', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, help_text='Auto-linked if a User with the same email exists.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculty_master_records', to=settings.AUTH_USER_MODEL, verbose_name='Linked User Account')),
            ],
            options={
                'verbose_name': 'Faculty Master',
                'verbose_name_plural': 'Faculty Master Records',
                'ordering': ['faculty_name'],
                'unique_together': {('academic_year', 'email')},
            },
        ),
        migrations.CreateModel(
            name='FacultyTeachingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('class_name', models.CharField(help_text='e.g., CV3, ME3, CE3+CSE3D, MLAI5B', max_length=100, verbose_name='Class')),
                ('is_coordinator', models.BooleanField(default=False, help_text='Whether this faculty is the Course Coordinator for this subject.', verbose_name='Course Coordinator')),
                ('teaching_type', models.CharField(choices=[('coordinator', 'Course Coordinator'), ('theory', 'Theory (All Students)'), ('practical_batch_a', 'Practical / Tutorial — Batch A'), ('practical_batch_b', 'Practical / Tutorial — Batch B'), ('practical_batch_c', 'Practical / Tutorial — Batch C')], default='theory', max_length=30, verbose_name='Teaching Type')),
                ('faculty_alias_raw', models.CharField(blank=True, help_text='The raw alias from the import file, kept for audit/debugging.', max_length=50, verbose_name='Original Alias')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='academic.academicyear', verbose_name='Academic Year')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_archived', to=settings.AUTH_USER_MODEL)),
                ('faculty', models.ForeignKey(blank=True, help_text='Null for External / unresolved faculty.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_assignments', to='academic.facultymaster', verbose_name='Faculty')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='academic.semester', verbose_name='Semester')),
                ('semester_subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teaching_assignments', to='academic.semestersubject', verbose_name='Subject')),
            ],
            options={
                'verbose_name': 'Faculty Teaching Assignment',
                'verbose_name_plural': 'Faculty Teaching Assignments',
                'ordering': ['semester', 'class_name', 'semester_subject'],
            },
        ),
        migrations.CreateModel(
            name='FacultyImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('import_type', models.CharField(choices=[('faculty_master', 'Faculty Master'), ('teaching_allocation', 'Teaching Allocation')], max_length=25, verbose_name='Import Type')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Original Filename')),
                ('file_format', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'Excel (XLSX)')], max_length=4, verbose_name='File Format')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial')], default='success', max_length=10, verbose_name='Import Status')),
                ('summary', models.JSONField(blank=True, default=dict, help_text='Statistics: records_created, records_updated, etc.', verbose_name='Import Summary')),
                ('error_log', models.JSONField(blank=True, default=list, help_text='List of row-level errors encountered during import.', verbose_name='Error Log')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_imports', to='academic.academicyear', verbose_name='Academic Year')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_archived', to=settings.AUTH_USER_MODEL)),
                ('imported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculty_imports', to=settings.AUTH_USER_MODEL, verbose_name='Imported By')),
            ],
            options={
                'verbose_name': 'Faculty Import Log',
                'verbose_name_plural': 'Faculty Import Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
