# Generated by Django 4.2.30 on 2026-06-30 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_faculty_master_and_allocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='end_date',
            field=models.DateField(blank=True, help_text='End date of the academic year.', null=True, verbose_name='End Date'),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='start_date',
            field=models.DateField(blank=True, help_text='Start date of the academic year.', null=True, verbose_name='Start Date'),
        ),
    ]
