# Generated by Django 6.0.4 on 2026-07-01 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0003_academicyear_end_date_academicyear_start_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MarksSubComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_archived", models.BooleanField(db_index=True, default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., Exam, Faculty Evaluation",
                        max_length=100,
                        verbose_name="Sub-Component Name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=100, verbose_name="Sub-Component Slug"),
                ),
                (
                    "max_marks",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Maximum Marks"
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Display Order"
                    ),
                ),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_archived",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "marks_component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_components",
                        to="academic.markscomponent",
                        verbose_name="Marks Component",
                    ),
                ),
            ],
            options={
                "verbose_name": "Marks Sub-Component",
                "verbose_name_plural": "Marks Sub-Components",
                "ordering": ["marks_component", "display_order", "name"],
                "unique_together": {("marks_component", "slug")},
            },
        ),
    ]
