# Generated by Django 6.0.4 on 2026-07-01 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0004_markssubcomponent"),
    ]

    operations = [
        migrations.AddField(
            model_name="markssubcomponent",
            name="number_of_questions",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Number of Questions"
            ),
        ),
    ]
