# Generated by Django 4.2.30 on 2026-06-17 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master_data', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField(verbose_name='Exam Date')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
                ('is_locked', models.BooleanField(default=False, help_text='If locked, auto-generation will not overwrite this record.', verbose_name='Is Locked')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_archived', to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='exams.exam')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules', to='master_data.subject')),
            ],
            options={
                'verbose_name': 'Exam Schedule',
                'verbose_name_plural': 'Exam Schedules',
                'ordering': ['date', 'start_time', 'subject__code'],
                'unique_together': {('exam', 'subject')},
            },
        ),
    ]
