# Generated by Django 6.0.4 on 2026-06-23 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("master_data", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubjectCoordinatorAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_archived", models.BooleanField(db_index=True, default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_archived",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "coordinator",
                    models.ForeignKey(
                        help_text="The faculty member designated as the Subject Coordinator.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coordinated_subjects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coordinator_assignments",
                        to="master_data.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subject Coordinator Assignment",
                "verbose_name_plural": "Subject Coordinator Assignments",
                "ordering": ["subject", "coordinator"],
                "unique_together": {("subject", "coordinator")},
            },
        ),
        migrations.CreateModel(
            name="SubjectFacultyAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_archived", models.BooleanField(db_index=True, default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "division_name",
                    models.CharField(
                        help_text="Text label for the division (e.g., 'A', 'B')",
                        max_length=50,
                        verbose_name="Division",
                    ),
                ),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_archived",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        help_text="The faculty member teaching this subject.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taught_subjects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faculty_assignments",
                        to="master_data.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subject Faculty Assignment",
                "verbose_name_plural": "Subject Faculty Assignments",
                "ordering": ["subject", "division_name", "faculty"],
                "unique_together": {("subject", "faculty", "division_name")},
            },
        ),
    ]
