# Generated by Django 6.0.4 on 2026-06-23 09:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("master_data", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_archived", models.BooleanField(db_index=True, default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "academic_year",
                    models.CharField(
                        help_text="Format: YYYY-YY (e.g., 2023-24)",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Format must be YYYY-YY (e.g., 2023-24)",
                                regex="^\\d{4}-\\d{2}$",
                            )
                        ],
                        verbose_name="Academic Year",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., Mid Semester 1 Examination",
                        max_length=255,
                        verbose_name="Exam Name",
                    ),
                ),
                (
                    "exam_type",
                    models.CharField(
                        choices=[
                            ("internal_1", "Internal 1"),
                            ("internal_2", "Internal 2"),
                            ("continuous", "Continuous Evaluation"),
                            ("other", "Other"),
                        ],
                        default="internal_1",
                        max_length=20,
                        verbose_name="Exam Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("ongoing", "Ongoing"),
                            ("completed", "Completed"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Exam Status",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Start Date")),
                ("end_date", models.DateField(verbose_name="End Date")),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_archived",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "programs",
                    models.ManyToManyField(
                        help_text="Select the programs participating in this exam.",
                        related_name="exams",
                        to="master_data.program",
                        verbose_name="Applicable Programs",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exam",
                "verbose_name_plural": "Exams",
                "ordering": ["-academic_year", "-start_date"],
            },
        ),
    ]
