# Generated by Django 4.2.30 on 2026-06-25 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='marks_entry_end',
            field=models.DateTimeField(blank=True, help_text='Faculty must finish entering marks by this date/time.', null=True, verbose_name='Marks Entry End'),
        ),
        migrations.AddField(
            model_name='exam',
            name='marks_entry_start',
            field=models.DateTimeField(blank=True, help_text='Faculty can begin entering marks from this date/time.', null=True, verbose_name='Marks Entry Start'),
        ),
    ]
