# Generated by Django 6.0.4 on 2026-06-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0002_exam_marks_entry_end_exam_marks_entry_start"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="exam_type",
            field=models.CharField(
                choices=[
                    ("I1", "I1 Examination"),
                    ("I2", "I2 Examination"),
                    ("Improvement", "Improvement Examination"),
                    ("FE", "FE Examination"),
                    ("PRACTICAL_CE", "Practical CE"),
                    ("THEORY_ESE", "Theory ESE"),
                    ("PRACTICAL_ESE", "Practical ESE"),
                    ("TUTORIAL_CE", "Tutorial CE"),
                    ("TUTORIAL_ESE", "Tutorial ESE"),
                ],
                default="I1",
                max_length=20,
                verbose_name="Exam Type",
            ),
        ),
    ]
