# Generated by Django 4.2.30 on 2026-06-29 04:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
        ('master_data', '0001_initial'),
        ('exams', '0003_alter_exam_exam_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['-start_date'], 'verbose_name': 'Exam', 'verbose_name_plural': 'Exams'},
        ),
        migrations.AddField(
            model_name='exam',
            name='academic_year_ref',
            field=models.ForeignKey(blank=True, help_text='Select the Academic Year this exam belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='academic.academicyear', verbose_name='Academic Year'),
        ),
        migrations.AddField(
            model_name='exam',
            name='semester_ref',
            field=models.ForeignKey(blank=True, help_text='Select the semester for this exam.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='academic.semester', verbose_name='Semester'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='academic_year',
            field=models.CharField(blank=True, default='', help_text='Format: YYYY-YY (e.g., 2023-24)', max_length=7, validators=[django.core.validators.RegexValidator(message='Format must be YYYY-YY (e.g., 2023-24)', regex='^\\d{4}-\\d{2}$')], verbose_name='Academic Year (Legacy)'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('THEORY_CE', 'Theory CE'), ('THEORY_ESE', 'Theory ESE'), ('PRACTICAL_CE', 'Practical CE'), ('PRACTICAL_ESE', 'Practical ESE'), ('TUTORIAL_CE', 'Tutorial CE'), ('TUTORIAL_ESE', 'Tutorial ESE'), ('I1', 'I1 Examination'), ('I2', 'I2 Examination'), ('Improvement', 'Improvement Examination'), ('FE', 'FE Examination')], default='THEORY_CE', max_length=20, verbose_name='Exam Type'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='programs',
            field=models.ManyToManyField(blank=True, help_text='Select the programs participating in this exam.', related_name='exams', to='master_data.program', verbose_name='Applicable Programs'),
        ),
    ]
