# Generated by Django 4.2.30 on 2026-06-30 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_alter_exam_options_exam_academic_year_ref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(help_text='Dynamically matches the MarksComponent name (e.g., Theory CE, Viva).', max_length=100, verbose_name='Exam / Component Type'),
        ),
    ]
