# Generated by Django 4.2.30 on 2026-06-25 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('seating_arrangement', 'Seating Arrangement'), ('duty_chart', 'Duty Chart'), ('marks_summary', 'Marks Summary'), ('result_analysis', 'Result Analysis'), ('exam_schedule', 'Exam Schedule'), ('question_paper', 'Question Paper')], max_length=50),
        ),
    ]
